### ISSUE TITLE
搜索词存在全角括号或者冒号时搜索不到内容

### ISSUE THREAD

**Issue by wankey** [fugary/calibre-douban#10]
搜索词存在全角括号或者冒号时搜索不到，改为半角符号就能搜索结果了。

calibre, version 5.44.0
错误： 无匹配项: <p>无法为你找到书籍元数据。请尝试<b>扩大搜索范围</b>。比如：只使用作者的名称或只包含标题中具有特征性的词组。<p>要查看完整的日志，请点击“查看详细信息”。

Running identify query with parameters: 
{'title': '深入浅出数据分析', 'authors': ['（美）米尔顿著'], 'identifiers': {}, 'timeout': 30} 
Using plugins: New Douban Books (1, 0, 7) 
The log from individual plugins is below 

****************************** New Douban Books (1, 0, 7) ****************************** 
Found 0 results 
Downloading from New Douban Books took 1.368743896484375 
Plugin New Douban Books failed
Traceback (most recent call last):
  File "calibre/ebooks/metadata/sources/identify.py", line 47, in run
  File "calibre_plugins.dummy1.__init__", line 293, in identify
    books = self.book_searcher.search_books(isbn or title, log)
  File "calibre_plugins.dummy1.__init__", line 65, in search_books
    book = future.result()
  File "concurrent/futures/_base.py", line 432, in result
  File "concurrent/futures/_base.py", line 388, in __get_result
  File "concurrent/futures/thread.py", line 57, in run
  File "calibre_plugins.dummy1.__init__", line 79, in load_book
    res = urlopen(Request(url, headers={'user-agent': random_user_agent()}))
  File "urllib/request.py", line 222, in urlopen
  File "urllib/request.py", line 531, in open
  File "urllib/request.py", line 640, in http_response
  File "urllib/request.py", line 569, in error
  File "urllib/request.py", line 502, in _call_chain
  File "urllib/request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 418: 

******************************************************************************** 
The identify phase took 1.43 seconds 
The longest time (1.368744) was taken by: New Douban Books 
Merging results from different sources 
We have 0 merged results, merging took: 0.00 seconds

**Comment by fugary** [comment]
418一般是防爬虫错误，全角应该不影响查询

**Comment by wankey** [comment]
> 418一般是防爬虫错误，全角应该不影响查询

主要是每次都是存在全角符号时报错，然后替换为半角或去除之后就正常了。
