### ISSUE TITLE
无法使用了，错位代码403

### ISSUE THREAD

**Issue by RnYi** [fugary/calibre-douban#11]
#################### Log for 控制论(或关于在动物和机器中控制和通信的科学) (科学元典丛书) ####################
Running identify query with parameters: 
{'title': '控制论(或关于在动物和机器中控制和通信的科学) (科学元典丛书)', 'authors': ['维纳'], 'identifiers': {'asin': 'B008H0V4QE'}, 'timeout': 30} 
Using plugins: New Douban Books (1, 0, 7) 
The log from individual plugins is below 

****************************** New Douban Books (1, 0, 7) ****************************** 
Found 0 results 
Downloading from New Douban Books took 0.6469862461090088 
Plugin New Douban Books failed
Traceback (most recent call last):
  File "calibre\ebooks\metadata\sources\identify.py", line 47, in run
  File "calibre_plugins.dummy1.__init__", line 293, in identify
  File "calibre_plugins.dummy1.__init__", line 61, in search_books
  File "calibre_plugins.dummy1.__init__", line 45, in load_book_urls
  File "urllib\request.py", line 216, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 634, in http_response
  File "urllib\request.py", line 557, in error
  File "urllib\request.py", line 496, in _call_chain
  File "urllib\request.py", line 749, in http_error_302
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 634, in http_response
  File "urllib\request.py", line 563, in error
  File "urllib\request.py", line 496, in _call_chain
  File "urllib\request.py", line 643, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden 

******************************************************************************** 
The identify phase took 0.83 seconds 
The longest time (0.646986) was taken by: New Douban Books 
Merging results from different sources 
We have 0 merged results, merging took: 0.00 seconds 
Failed to download metadata for 控制论(或关于在动物和机器中控制和通信的科学) (科学元典丛书) 

****************************** New Douban Books Covers ****************************** 
Request extra headers: [('User-agent', 'Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko')] 
Failed to download valid cover 
Took 0.6448569297790527 seconds 
No cached cover found, running identify
Failed to download cover from New Douban Books
Traceback (most recent call last):
  File "calibre\ebooks\metadata\sources\covers.py", line 46, in run
  File "calibre_plugins.dummy1.__init__", line 227, in download_cover
  File "calibre_plugins.dummy1.__init__", line 293, in identify
  File "calibre_plugins.dummy1.__init__", line 61, in search_books
  File "calibre_plugins.dummy1.__init__", line 45, in load_book_urls
  File "urllib\request.py", line 216, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 634, in http_response
  File "urllib\request.py", line 557, in error
  File "urllib\request.py", line 496, in _call_chain
  File "urllib\request.py", line 749, in http_error_302
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 634, in http_response
  File "urllib\request.py", line 563, in error
  File "urllib\request.py", line 496, in _call_chain
  File "urllib\request.py", line 643, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden 

********************************************************************************

**Comment by choleraehyq** [comment]
我也遇到了一样的问题

**Comment by fugary** [comment]
403是没有权限，一般都是访问多了被豆瓣拦了

**Comment by fugary** [comment]
已修复这个问题，获取书籍列表的地址被屏蔽了，改成直接用网页获取列表
