### ISSUE TITLE
远程端关闭连接,无响应错误

### ISSUE THREAD

**Issue by wwhRyan** [fugary/calibre-douban#13]
Windows PC平台下
calibre: 6.21.0版本
calibre-douban 插件: [v2.0.0](https://github.com/fugary/calibre-douban/tree/v2.0.0)

错误日志:
`
#################### Log for 朗读者 ####################
Running identify query with parameters: 
{'title': '朗读者', 'authors': ['[德国] 本哈德·施林克', '钱定平'], 'identifiers': {'mobi-asin': '049db565-dd65-4907-a8d6-07f2505a6ae9', 'isbn': '9787544707923'}, 'timeout': 30} 
Using plugins: New Douban Books (2, 0, 0) 
The log from individual plugins is below 

****************************** New Douban Books (2, 0, 0) ****************************** 
Found 0 results 
Downloading from New Douban Books took 0.051558494567871094 
Plugin New Douban Books failed
Traceback (most recent call last):
  File "urllib\request.py", line 1348, in do_open
  File "http\client.py", line 1282, in request
  File "http\client.py", line 1328, in _send_request
  File "http\client.py", line 1277, in endheaders
  File "http\client.py", line 1037, in _send_output
  File "http\client.py", line 975, in send
  File "http\client.py", line 1447, in connect
  File "http\client.py", line 951, in connect
  File "http\client.py", line 920, in _tunnel
  File "http\client.py", line 287, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\ebooks\metadata\sources\identify.py", line 47, in run
  File "calibre_plugins.dummy1.__init__", line 326, in identify
  File "calibre_plugins.dummy1.__init__", line 63, in search_books
  File "calibre_plugins.dummy1.__init__", line 48, in load_book_urls_new
  File "urllib\request.py", line 216, in urlopen
  File "urllib\request.py", line 519, in open
  File "urllib\request.py", line 536, in _open
  File "urllib\request.py", line 496, in _call_chain
  File "urllib\request.py", line 1391, in https_open
  File "urllib\request.py", line 1351, in do_open
urllib.error.URLError: <urlopen error Remote end closed connection without response> 

******************************************************************************** 
The identify phase took 0.21 seconds 
The longest time (0.051558) was taken by: New Douban Books 
Merging results from different sources 
We have 0 merged results, merging took: 0.00 seconds 
Failed to download metadata for 朗读者 

****************************** New Douban Books Covers ****************************** 
Request extra headers: [('User-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75')] 
Failed to download valid cover 
Took 0.014216899871826172 seconds 
No cached cover found, running identify
Failed to download cover from New Douban Books
Traceback (most recent call last):
  File "urllib\request.py", line 1348, in do_open
  File "http\client.py", line 1282, in request
  File "http\client.py", line 1328, in _send_request
  File "http\client.py", line 1277, in endheaders
  File "http\client.py", line 1037, in _send_output
  File "http\client.py", line 975, in send
  File "http\client.py", line 1447, in connect
  File "http\client.py", line 951, in connect
  File "http\client.py", line 920, in _tunnel
  File "http\client.py", line 287, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\ebooks\metadata\sources\covers.py", line 46, in run
  File "calibre_plugins.dummy1.__init__", line 261, in download_cover
  File "calibre_plugins.dummy1.__init__", line 326, in identify
  File "calibre_plugins.dummy1.__init__", line 63, in search_books
  File "calibre_plugins.dummy1.__init__", line 48, in load_book_urls_new
  File "urllib\request.py", line 216, in urlopen
  File "urllib\request.py", line 519, in open
  File "urllib\request.py", line 536, in _open
  File "urllib\request.py", line 496, in _call_chain
  File "urllib\request.py", line 1391, in https_open
  File "urllib\request.py", line 1351, in do_open
urllib.error.URLError: <urlopen error Remote end closed connection without response> 

******************************************************************************** 
`

请问这个ISSUE是什么原因造成的呢?谢谢

**Comment by wwhRyan** [comment]
> 看起来是封面图下载失败，是否是本地网络问题，重试看看

@fugary 谢谢回复,通过chrome访问对应的api,是有书籍的元数据回复的.对比测试,应该是我电脑本地网络设置有问题.

本地网络的问题我还得再研究一下.
