### ISSUE TITLE
豆瓣403了

### ISSUE THREAD

**Issue by rerbin** [fugary/calibre-douban#15]
麻烦修复一下

**Comment by fugary** [comment]
刚还试了下，没有问题啊，是不是抓取频繁被拦了，可以等一段时间再试或者登录账号把cookie填进去，参考文档：https://fugary.com/?p=423

**Comment by ChouSkim** [comment]
```
******************************` New Douban Books (2, 0, 1) ****************************** 
Found 0 results 
Downloading from New Douban Books took 8.697023868560791 
Random sleep time 0.013196636524950978s
Random sleep time 0.03457691943154163s
Random sleep time 0.05430206628676855s
Random sleep time 0.04697191791639523s
Random sleep time 0.0038138277025330457s
Downloaded:https://book.douban.com/subject/26636067/ Successful,Time 5161ms
Downloaded:https://book.douban.com/subject/21993088/ Successful,Time 5268ms
Plugin New Douban Books failed
Traceback (most recent call last):
  File "site-packages\calibre\ebooks\metadata\sources\identify.py", line 47, in run
  File "calibre_plugins.dummy1.__init__", line 328, in identify
  File "calibre_plugins.dummy1.__init__", line 68, in search_books
  File "concurrent\futures\_base.py", line 432, in result
  File "concurrent\futures\_base.py", line 388, in __get_result
  File "concurrent\futures\thread.py", line 57, in run
  File "calibre_plugins.dummy1.__init__", line 82, in load_book
  File "calibre_plugins.dummy1.__init__", line 113, in parse_book
AttributeError: 'NoneType' object has no attribute 'xpath'

Downloaded:https://book.douban.com/subject/1939989/ Successful,Time 5653ms
Downloaded:https://book.douban.com/subject/2154092/ Successful,Time 6515ms
Downloaded:https://book.douban.com/subject/1340758/ Successful,Time 10528ms 
```

这个AttributeError很早之前就发生了，看上去是成功找到了连接，但没有办法显示。

**Comment by ChouSkim** [comment]
403的问题也有过，不过看似定期更新一下Cookie是可以解决的。
