### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'xpath'

### ISSUE THREAD

**Issue by ChouSkim** [fugary/calibre-douban#17]
```
****************************** New Douban Books (2, 0, 1) ****************************** 
Found 0 results 
Downloading from New Douban Books took 8.697023868560791 
Random sleep time 0.013196636524950978s
Random sleep time 0.03457691943154163s
Random sleep time 0.05430206628676855s
Random sleep time 0.04697191791639523s
Random sleep time 0.0038138277025330457s
Downloaded:https://book.douban.com/subject/26636067/ Successful,Time 5161ms
Downloaded:https://book.douban.com/subject/21993088/ Successful,Time 5268ms
Plugin New Douban Books failed
Traceback (most recent call last):
  File "site-packages\calibre\ebooks\metadata\sources\identify.py", line 47, in run
  File "calibre_plugins.dummy1.__init__", line 328, in identify
  File "calibre_plugins.dummy1.__init__", line 68, in search_books
  File "concurrent\futures\_base.py", line 432, in result
  File "concurrent\futures\_base.py", line 388, in __get_result
  File "concurrent\futures\thread.py", line 57, in run
  File "calibre_plugins.dummy1.__init__", line 82, in load_book
  File "calibre_plugins.dummy1.__init__", line 113, in parse_book
AttributeError: 'NoneType' object has no attribute 'xpath'

Downloaded:https://book.douban.com/subject/1939989/ Successful,Time 5653ms
Downloaded:https://book.douban.com/subject/2154092/ Successful,Time 6515ms
Downloaded:https://book.douban.com/subject/1340758/ Successful,Time 10528ms 
```

Calibre版本：5.1
New Douban插件已安装，并填写Cookie信息，但不知为何报了AttributeError，是插件相关的错误么？是否可以加一个Exception忽略掉？

时间线补充：
- 大约一年前左右初安装时，能够成功获取元数据
- 之后某次使用时发现豆瓣更新了安全规则，参照文档添加了Cookie后，能够成功获取元数据

如需要提供其他相关日志信息，请说明。

**Comment by fugary** [comment]
是所有书还是部分书有问题，如果是部分，提供下书名或isbn号

**Comment by fugary** [comment]
优化了一下，可以再试试看

**Comment by ChouSkim** [comment]
> 是所有书还是部分书有问题，如果是部分，提供下书名或isbn号

也许是部分书，我再尝试了一下，发现也许是因为我采用https://zhuanlan.zhihu.com/p/640104300中的方法，把Calibre的文件夹目录改为中文显示的缘故。英文书籍能够正常获取信息，但中文书籍会报AttributeError的错误。
我先试试看新版本插件，看看能否解决问题。

**Comment by ChouSkim** [comment]
> 优化了一下，可以再试试看

AttributeError的问题已解决。关于识别准确定的问题我在另一个Issue里补充说明一下。
