### ISSUE TITLE
异常IP无法下载元数据怎么办

### ISSUE THREAD

**Issue by aghao** [fugary/calibre-douban#8]
也就用了3-4次，都挺成功的，在PC端5.x.x版本的Calibre，但是再用就用不了了，用浏览器打开豆瓣读书提示异常IP需要登录，登录以后再用Calibre来获取也不行，怎么办

**Comment by aghao** [comment]
The log from individual plugins is below 

****************************** New Douban Books (1, 0, 6) ****************************** 
Found 0 results 
Downloading from New Douban Books took 0.4141063690185547 
Plugin New Douban Books failed
Traceback (most recent call last):
  File "calibre\ebooks\metadata\sources\identify.py", line 47, in run
  File "calibre_plugins.dummy2.__init__", line 283, in identify
  File "calibre_plugins.dummy2.__init__", line 61, in search_books
  File "calibre_plugins.dummy2.__init__", line 45, in load_book_urls
  File "urllib\request.py", line 222, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 563, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 755, in http_error_302
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden 

********************************************************************************

**Comment by fugary** [comment]
一般不会那么快封IP，并发数默认也就5个，封了之后一般更换一个IP就可以了，比如路由器重连下宽带

**Comment by aghao** [comment]
确实快，不过用了下爱加速试用以后再断开，一会儿又好了，是不是有时间限制？查询5次之后需要间隔多久再开始查询下一次比较好
(都是使用插件手动查询

Gary Fu ***@***.***> 于 2022年6月18日周六 09:08写道：
